baseURL: https://hemendra.in/
languageCode: en-us
title: Hemendra Singh Rajawat
theme: [PaperMod]
timeZone: "Asia/Kolkata"
googleAnalytics: G-9VJ1M639JP

taxonomies:
    category: categories
    tag: tags

minify:
  disableXML: true
  minifyOutput: true

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: 10
        - identifier: blog
          name: Blog
          url: /blog
          weight: 20
        - identifier: projects
          name: Projects
          url: /projects
          weight: 30
        - identifier: experience
          name: Experience
          url: /experience
          weight: 40
        - identifier: search
          name: Search
          url: /search
          weight: 50
        - name: Tags
          url: tags/
          weight: 60

params:
    defaultTheme: auto
    env: production
    description: Portfolio and blog website of Hemendra about tech, ai/ml, and projects.
    DateFormat: "January 2, 2006"

    footer:
      showPoweredBy: false
      text: "[Privacy Policy](/privacy \"Privacy Policy\") ¬∑ [RSS Feed](/index.xml \"Really Simple Syndication Feed\")"

    profileMode:
        enabled: true
        title: Hemendra Singh Rajawat
        subtitle: "
        **Senior Consultant at Deloitte** <br>
        Salesforce | Machine Learning & Data Science ü§ñüìä
        <br><br>
        I am a Salesforce and TensorFlow certified developer, currently transitioning deeper into Machine Learning and Data Science by working on hands-on, end-to-end ML projects using Python and TensorFlow.
        <br>
        Through this site üåê, I document my learning journey ‚úçÔ∏è, share technical insights üìò, and showcase applied machine learning work with a strong focus on real-world problem solving üß©üöÄ. Outside of work and code, I‚Äôm an avid cyclist üö¥‚Äç‚ôÇÔ∏è who enjoys pushing limits‚Äîon the road and in technology ‚öôÔ∏èüî•.
        
        "
        imageUrl: home/me.jpg
        imageWidth: 220
        imageHeight: 220
        buttons:
            - name: ‚Üì Resume
              url: home/hemendra_resume.pdf

    socialIcons:
        - name: email
          url: mailto:hemendra.rajawat@outlook.com
        - name: linkedin
          url: https://www.linkedin.com/in/hsrajawat/
        - name: github
          url: https://github.com/hemendrarajawat
        - name: kaggle
          url: https://www.kaggle.com/hemendrasr
        - name: rss
          url: /index.xml

    ShowFullTextinRSS: true
    ShowRssButtonInSectionTermList: true
    ShowShareButtons: true
    ShowReadingTime: true
    ShowWordCount: false
    ShowToc: true
    TocOpen: false
    ShowBreadCrumbs: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    hideDescriptionInList: false
    math: true

    cover:
        hidden: false
        linkFullImages: false
        hiddenInList: false
        hiddenInSingle: true

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content", "description"]

outputs:
    home:
        - HTML
        - RSS
        - JSON

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true

privacy:
  googleAnalytics:
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true